import { migrateScenario } from './scenario';
import { Scenario } from '../types';

export function getSampleScenarios(): Scenario[] {
  const data = [
    {
      "id": 14,
      "scenarioName": "Mastercard (MA) - Reverse DCF",
      "dcfMethod": "Basic DCF",
      "buyPrice": 521.32,
      "years": 5,
      "discountRate": 10,
      "exitAssumptionType": "Yield",
      "exitMultiple": "",
      "exitYield": 3.75,
      "perpetuityGrowthRate": 2,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 12,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "niCurrentMetricPerShare": 16.56,
      "niCurrentMetricTotal": 15000,
      "niFinalMargin": "",
      "customCurrentMetricPerShare": "",
      "customCurrentMetricTotal": "",
      "customFinalMargin": "",
      "splitYears": [],
      "projectionMethod": "Per Share Method",
      "metricGrowthRates": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "metricGrowthRatesTotal": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "revenueGrowthRates": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "finalMargins": [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
      "sharesGrowthRates": [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
      "currentMetricPerShare": 17.66,
      "currentMetricTotal": 16000,
      "currentRevenue": 32800,
      "currentShares": 906,
      "inMillions": true
    },
    {
      "id": 16,
      "scenarioName": "Mastercard (MA) - Base Case",
      "dcfMethod": "Basic DCF",
      "buyPrice": 521.32,
      "years": 5,
      "discountRate": 10,
      "exitAssumptionType": "Yield",
      "exitMultiple": "",
      "exitYield": 3.25,
      "perpetuityGrowthRate": 2,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 14,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "niCurrentMetricPerShare": 16.56,
      "niCurrentMetricTotal": 15000,
      "niFinalMargin": "",
      "customCurrentMetricPerShare": "",
      "customCurrentMetricTotal": "",
      "customFinalMargin": "",
      "splitYears": [],
      "projectionMethod": "Per Share Method",
      "metricGrowthRates": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "metricGrowthRatesTotal": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "revenueGrowthRates": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "finalMargins": [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
      "sharesGrowthRates": [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
      "currentMetricPerShare": 17.66,
      "currentMetricTotal": 16000,
      "currentRevenue": 32800,
      "currentShares": 906,
      "inMillions": true
    },
    {
      "id": 18,
      "scenarioName": "Mastercard (MA) - Bull Case",
      "dcfMethod": "Basic DCF",
      "buyPrice": 521.32,
      "years": 5,
      "discountRate": 10,
      "exitAssumptionType": "Yield",
      "exitMultiple": "",
      "exitYield": 3,
      "perpetuityGrowthRate": 2,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 16,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "niCurrentMetricPerShare": "",
      "niCurrentMetricTotal": "",
      "niFinalMargin": "",
      "customCurrentMetricPerShare": "",
      "customCurrentMetricTotal": "",
      "customFinalMargin": "",
      "splitYears": [],
      "projectionMethod": "Per Share Method",
      "metricGrowthRates": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "metricGrowthRatesTotal": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "revenueGrowthRates": [10, 5, 5, 5, 5, 5, 5, 5, 5, 5],
      "finalMargins": [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
      "sharesGrowthRates": [-2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
      "currentMetricPerShare": 17.66,
      "currentMetricTotal": 500,
      "currentRevenue": 1000,
      "currentShares": 100,
      "inMillions": true
    },
    {
      "id": 20,
      "scenarioName": "Mastercard (MA) - Advanced DCF, 2 Phases",
      "dcfMethod": "Advanced DCF",
      "buyPrice": 521.32,
      "years": 10,
      "discountRate": 10,
      "exitAssumptionType": "Perpetuity Growth",
      "exitMultiple": "",
      "exitYield": 3,
      "perpetuityGrowthRate": 3.5,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": "",
      "simpleMetricGrowthRateTotal": "",
      "simpleRevenueGrowthRate": "",
      "simpleFinalMargin": "",
      "simpleSharesGrowthRate": "",
      "niCurrentMetricPerShare": "",
      "niCurrentMetricTotal": "",
      "niFinalMargin": "",
      "customCurrentMetricPerShare": "",
      "customCurrentMetricTotal": "",
      "customFinalMargin": "",
      "splitYears": [6],
      "projectionMethod": "Total FCF, Share Count",
      "metricGrowthRates": [10, 10, 5, 5, 5, 5, 5, 5, 5, 5],
      "metricGrowthRatesTotal": [14, 10, 5, 5, 5, 5, 5, 5, 5, 5],
      "revenueGrowthRates": [10, 10, 5, 5, 5, 5, 5, 5, 5, 5],
      "finalMargins": [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
      "sharesGrowthRates": [-2, -2, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
      "currentMetricPerShare": 10,
      "currentMetricTotal": 17090,
      "currentRevenue": 1000,
      "currentShares": 898,
      "inMillions": true
    },
    {
      "id": 22,
      "scenarioName": "Mastercard (MA) - Advanced DCF, 3 Phases",
      "dcfMethod": "Advanced DCF",
      "buyPrice": 521.32,
      "years": 15,
      "discountRate": 10,
      "exitAssumptionType": "Perpetuity Growth",
      "exitMultiple": "",
      "exitYield": 3,
      "perpetuityGrowthRate": 3.5,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": "",
      "simpleMetricGrowthRateTotal": "",
      "simpleRevenueGrowthRate": "",
      "simpleFinalMargin": "",
      "simpleSharesGrowthRate": "",
      "niCurrentMetricPerShare": "",
      "niCurrentMetricTotal": "",
      "niFinalMargin": "",
      "customCurrentMetricPerShare": "",
      "customCurrentMetricTotal": "",
      "customFinalMargin": "",
      "splitYears": [6, 11],
      "projectionMethod": "Total FCF, Share Count",
      "metricGrowthRates": [10, 10, 10, 10, 5, 5, 5, 5, 5, 5],
      "metricGrowthRatesTotal": [14, 10, 6, 10, 5, 5, 5, 5, 5, 5],
      "revenueGrowthRates": [10, 10, 10, 10, 5, 5, 5, 5, 5, 5],
      "finalMargins": [20, 20, 20, 20, 20, 20, 20, 20, 20, 20],
      "sharesGrowthRates": [-2, -2, -2, -2, -2.5, -2.5, -2.5, -2.5, -2.5, -2.5],
      "currentMetricPerShare": 10,
      "currentMetricTotal": 17090,
      "currentRevenue": 1000,
      "currentShares": 898,
      "inMillions": true
    }
  ];

  return data.map(item => migrateScenario(item));
}
