export function getSampleScenarios(): any[] {
  return [
    {
      "id": 1,
      "scenarioName": "Mastercard (MA) - Reverse DCF",
      "dcfMethod": "Basic DCF",
      "buyPrice": 498,
      "years": 5,
      "discountRate": 10,
      "exitAssumptionType": "Yield",
      "exitMultiple": 10,
      "exitYield": 3.75,
      "perpetuityGrowthRate": 2,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 12,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "splitYears": [],
      "projectionMethod": "Per Share Method",
      "currentMetricPerShare": 10,
      "metricGrowthRates": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentMetricTotal": 500,
      "metricGrowthRatesTotal": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentRevenue": 1000,
      "revenueGrowthRates": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "finalMargins": [
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20
      ],
      "inMillions": true,
      "currentShares": 100,
      "sharesGrowthRates": [
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5
      ]
    },
    {
      "id": 57,
      "scenarioName": "Mastercard (MA) - Base Case",
      "dcfMethod": "Basic DCF",
      "buyPrice": 498,
      "years": 5,
      "discountRate": 10,
      "exitAssumptionType": "Yield",
      "exitMultiple": 10,
      "exitYield": 3.25,
      "perpetuityGrowthRate": 2,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 14,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "splitYears": [],
      "projectionMethod": "Per Share Method",
      "currentMetricPerShare": 10,
      "metricGrowthRates": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentMetricTotal": 500,
      "metricGrowthRatesTotal": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentRevenue": 1000,
      "revenueGrowthRates": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "finalMargins": [
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20
      ],
      "inMillions": true,
      "currentShares": 100,
      "sharesGrowthRates": [
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5
      ]
    },
    {
      "id": 114,
      "scenarioName": "Mastercard (MA) - Bull Case",
      "dcfMethod": "Basic DCF",
      "buyPrice": 498,
      "years": 5,
      "discountRate": 10,
      "exitAssumptionType": "Yield",
      "exitMultiple": 10,
      "exitYield": 3,
      "perpetuityGrowthRate": 2,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 16,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "splitYears": [],
      "projectionMethod": "Per Share Method",
      "currentMetricPerShare": 10,
      "metricGrowthRates": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentMetricTotal": 500,
      "metricGrowthRatesTotal": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentRevenue": 1000,
      "revenueGrowthRates": [
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "finalMargins": [
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20
      ],
      "inMillions": true,
      "currentShares": 100,
      "sharesGrowthRates": [
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5
      ]
    },
    {
      "id": 192,
      "scenarioName": "Mastercard (MA) - Advanced DCF, 2 Phases",
      "dcfMethod": "Advanced DCF",
      "buyPrice": 498,
      "years": 10,
      "discountRate": 10,
      "exitAssumptionType": "Perpetuity Growth",
      "exitMultiple": 10,
      "exitYield": 3,
      "perpetuityGrowthRate": 3.5,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 16,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "splitYears": [
        6
      ],
      "projectionMethod": "Total FCF, Share Count",
      "currentMetricPerShare": 10,
      "metricGrowthRates": [
        10,
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentMetricTotal": 17090,
      "metricGrowthRatesTotal": [
        14,
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentRevenue": 1000,
      "revenueGrowthRates": [
        10,
        10,
        5,
        5,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "finalMargins": [
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20
      ],
      "inMillions": true,
      "currentShares": 898,
      "sharesGrowthRates": [
        -2,
        -2,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5
      ]
    },
    {
      "id": 380,
      "scenarioName": "Mastercard (MA) - Advanced DCF, 3 Phases",
      "dcfMethod": "Advanced DCF",
      "buyPrice": 498,
      "years": 15,
      "discountRate": 10,
      "exitAssumptionType": "Perpetuity Growth",
      "exitMultiple": 10,
      "exitYield": 3,
      "perpetuityGrowthRate": 3.5,
      "simpleProjectionMethod": "Per Share",
      "simpleMetricType": "Free Cash Flow",
      "simpleCustomMetric": "",
      "simpleMetricGrowthRate": 16,
      "simpleMetricGrowthRateTotal": 10,
      "simpleRevenueGrowthRate": 10,
      "simpleFinalMargin": 20,
      "simpleSharesGrowthRate": -2.5,
      "splitYears": [
        6,
        11
      ],
      "projectionMethod": "Total FCF, Share Count",
      "currentMetricPerShare": 10,
      "metricGrowthRates": [
        10,
        10,
        10,
        10,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentMetricTotal": 17090,
      "metricGrowthRatesTotal": [
        14,
        10,
        6,
        10,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "currentRevenue": 1000,
      "revenueGrowthRates": [
        10,
        10,
        10,
        10,
        5,
        5,
        5,
        5,
        5,
        5
      ],
      "finalMargins": [
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20,
        20
      ],
      "inMillions": true,
      "currentShares": 898,
      "sharesGrowthRates": [
        -2,
        -2,
        -2,
        -2,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5,
        -2.5
      ]
    }
  ];
}
